/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import com.example.entity.Dvd;
import com.example.repository.DvdRepository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import java.util.Optional;

import static org.hamcrest.MatcherAssert.*;
import static org.hamcrest.CoreMatchers.*;

@DataJpaTest
class TestDvdRepository {

    @Autowired
    private DvdRepository dvdRepository;

    @Test public void when_dvdRepositoryFindAll_then_noErrorAndNoResult() {
        //given

        //when
        Iterable<Dvd> dvds = dvdRepository.findAll();

        //then
        assertThat(dvds, notNullValue());
        assertThat(dvds.iterator().hasNext(), is(false));
    }

    @Test public void when_emptyDvdRepositoryFindByTitle_then_noErrorAndNoResult() {
        //given

        //when
        Dvd dvd = dvdRepository.findByTitle("A Few Good Men");

        //then
        assertThat(dvd, nullValue());
    }

    @Test public void when_saveDvd_then_dvdIsSaved() {
        //given
        Dvd newDvd = new Dvd();
        newDvd.setTitle("A Few Good Men");
        newDvd.setRunningTimeInSeconds(234);

        //when
        Dvd savedDvd = dvdRepository.save(newDvd);
        Optional<Dvd> readDvdHolder = dvdRepository.findById(savedDvd.getId());

        //then
        assertThat(savedDvd, notNullValue());
        assertThat(savedDvd.getId(), notNullValue());
        assertThat(savedDvd.getRunningTimeInSeconds(), equalTo(234));
        assertThat(savedDvd.getTitle(), equalTo("A Few Good Men"));

        assertThat(readDvdHolder.isPresent(), equalTo(true));
        assertThat(readDvdHolder.get(), equalTo(savedDvd));
    }
}
